language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fission' ]; then cd .. && eval "mv $currentfolder generator-fission" && cd generator-fission; fi

